### ISSUE TITLE
Please provide default configuration.

### ISSUE THREAD

**Issue by HarelM** [zoomsphere/angular2-localstorage#4]
IMHO there should not be extra script tag for configuration if possible (I would like to keep my index.html file as clean as possible).
I migrated from previous version and it broke (as opposed to fully backward compatible ;-)).

**Comment by DanielKucal** [comment]
Hi @HarelM, you don't need the script when want to use [default config](https://github.com/zoomsphere/ngx-store/blob/master/src/config/config.ts#L8) which is the following:
```
const DefaultConfig: WebStorageConfigInterface = {
    prefix: 'ngx_',
    previousPrefix: 'angular2ws_',
    clearType: 'prefix',
    mutateObjects: true,
};
```
The configuration has to be passed before Angular application to provide it into decorating functions that are executed immediately. You can look for other solution in your app.
Did you migrate from straight `angular2-localstorage` or have been using custom prefix before? Have you investigated what is the exact problem?

**Comment by HarelM** [comment]
I was using this repo since I started with angular 4. Upgraded from 0.51.
The error I'm getting is that I didn't define the config object, I was hoping this would be optional.

**Comment by DanielKucal** [comment]
You are right, I can't believe I haven't tested this scenario. Thanks for reporting this. Fix is included in `v0.6.1`, please let me know if related problem still occurs or close it otherwise, thanks in advance!

**Comment by HarelM** [comment]
Seem to fix the issue, thanks!
Will the following code change only the prefix (my manual tests shows that it doesn't...)?
```
import { enableProdMode } from "@angular/core";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { WEBSTORAGE_CONFIG } from "ngx-store";
import { ApplicationModule } from "./application/application.module";
import { environment } from "./environments/environment";

WEBSTORAGE_CONFIG.prefix = "IHM.";

if (environment.production) {
  enableProdMode();
}
platformBrowserDynamic().bootstrapModule(ApplicationModule);
```

I tried to change the prefix value but it seem to remember the stored values, so I guess I miss-configured it. 
Is there a way to configure the values from typescript code? (`ng build` is hiding all the webpack etc and I would like to configure it from typescript code).

**Comment by DanielKucal** [comment]
Unfortunately not, that's why `WEBSTORAGE_CONFIG` is marked as deprecated. It's all because the decorating functions can't wait for config... Maybe we will invite something smarter in the future, but for now the only recommended ways to do it are listed in readme.

**Comment by HarelM** [comment]
I thought so, I'll just use the default... Thanks for the super quick response!

**Comment by DanielKucal** [comment]
Thanks for your appreciation, I wrote it when should be stepping out of a train 😆
